const test = require('node:test');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {execFileSync} = require('node:child_process');

test('V1 and V2 use separate ownership, reject wrong-version writes, and fence old tasks after a switch', () => {
  const root = path.resolve(__dirname, '../../../..');
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'director-versions-'));
  const script = path.join(dir, 'drill.cjs');
  fs.writeFileSync(script, String.raw`
const assert = require('node:assert/strict');
const path = require('node:path');
const server = path.join(process.env.DIRECTOR_NEXT_REPO_ROOT, 'server');
const {prisma} = require(path.join(server, 'dist/db/prisma'));
const {ensureRuntimeDatabaseReady} = require(path.join(server, 'dist/db/runtimeMigrations'));
(async () => {
  await ensureRuntimeDatabaseReady();
  await prisma.novel.create({data:{id:'v1-book',title:'原导演小说'}});
  await prisma.novel.create({data:{id:'v2-book',title:'新导演小说'}});
  await prisma.chapter.create({data:{id:'saved',novelId:'v2-book',order:1,title:'保存版',content:'保留这段已保存正文。'}});
  const {createApp} = require(path.join(server, 'dist/app'));
  const http = createApp().listen(0);
  await new Promise(resolve => http.once('listening', resolve));
  const base = 'http://127.0.0.1:' + http.address().port;
  const request = async (url, method='GET', body) => {
    const res = await fetch(base + url, {method, headers:{'Content-Type':'application/json'}, ...(body ? {body:JSON.stringify(body)} : {})});
    return {status:res.status, body:await res.json()};
  };
  try {
    const first = await request('/api/novels/v1-book/director-version');
    assert.equal(first.status, 200, 'version selection must be available without starting production');
    assert.equal(first.body.data.version, 'v1');
    assert.equal(first.body.data.epoch, 0);
    assert.deepEqual(first.body.data.availableVersions, ['v1','v2']);
    const switched = await request('/api/novels/v2-book/director-version', 'PUT', {version:'v2', expectedEpoch:0});
    assert.equal(switched.status, 200);
    assert.equal(switched.body.data.version, 'v2');
    assert.equal(switched.body.data.epoch, 1);
    const shelf = await request('/api/novels?limit=24');
    assert.equal(shelf.body.data.items.find(x=>x.id==='v1-book').workspaceSourceRoute, null);
    assert.equal(shelf.body.data.items.find(x=>x.id==='v2-book').workspaceSourceRoute, '/lab/director/v2-book');
    const prose = await prisma.chapter.findUnique({where:{id:'saved'}});
    const beforeTasks = await prisma.novelWorkflowTask.findMany();
    const wrongV1 = await request('/api/novels/director/novels/v2-book/commands', 'POST', {commandType:'continue',payload:{}});
    assert.equal(wrongV1.status, 409);
    const wrongV2 = await request('/api/director-next/commands', 'POST', {type:'open_run',novelId:'v1-book',driver:'auto',stepIdsInScope:null,idempotencyKey:'wrong-v2',launchInput:{storyInput:'不得执行',estimatedChapterCount:3,worldMode:'skip',provider:'openai',model:'no-real-call'}});
    assert.equal(wrongV2.status, 409);
    assert.deepEqual(await prisma.novelWorkflowTask.findMany(), beforeTasks);
    assert.equal(await prisma.directorNextRun.count(), 0);
    assert.deepEqual(await prisma.chapter.findUnique({where:{id:'saved'}}), prose);
    const ownership = require(path.join(server, 'dist/modules/novel/director-routing'));
    await prisma.novelWorkflowTask.create({data:{id:'historic-opening',title:'历史开书任务',lane:'auto_director',status:'succeeded'}});
    const historicOpening=await prisma.novelWorkflowTask.findUnique({where:{id:'historic-opening'}});
    await assert.rejects(ownership.readOpeningVersion('historic-opening','v2'),error=>error.statusCode===409,'unbound historical tasks freeze V1 rather than adopting a requested V2 version');
    assert.equal((await request('/api/novel-workflows/bootstrap','POST',{lane:'auto_director',workflowTaskId:'historic-opening',seedPayload:{directorVersion:'v2'}})).status,409);
    assert.deepEqual(await prisma.novelWorkflowTask.findUnique({where:{id:'historic-opening'}}),historicOpening);
    assert.deepEqual((await request('/api/novels/director-versions')).body.data,{availableVersions:['v1','v2'],defaultVersion:'v2'});
    await prisma.novel.create({data:{id:'race-book',title:'并发切换'}});
    const race=await Promise.all([request('/api/novels/race-book/director-version','PUT',{version:'v2',expectedEpoch:0}),request('/api/novels/race-book/director-version','PUT',{version:'v2',expectedEpoch:0})]);
    assert.deepEqual(race.map(result=>result.status).sort(),[200,409]);
    assert.equal((await prisma.novel.findUnique({where:{id:'race-book'}})).directorEpoch,1);
    await prisma.novelWorkflowTask.create({data:{id:'v1-task',title:'V1 生产',novelId:'v1-book',lane:'auto_director',status:'queued',directorVersion:'v1',directorEpoch:0}});
    assert.equal((await request('/api/novels/v1-book/director-version','PUT',{version:'v2',expectedEpoch:0})).status,409);
    await prisma.novelWorkflowTask.update({where:{id:'v1-task'},data:{status:'succeeded'}});
    await prisma.directorRunCommand.create({data:{id:'terminal-task-command',taskId:'v1-task',commandType:'continue',idempotencyKey:'terminal-task-command',status:'queued',payloadJson:'{}'}});
    assert.equal((await request('/api/novels/v1-book/director-version','PUT',{version:'v2',expectedEpoch:0})).status,409,'an accepted queued command still blocks switching when its task is terminal');
    await prisma.directorRunCommand.update({where:{id:'terminal-task-command'},data:{status:'succeeded'}});
    assert.equal((await request('/api/novels/v1-book/director-version','PUT',{version:'v2',expectedEpoch:0})).status,200);
    assert.equal((await request('/api/novels/v1-book/director-version','PUT',{version:'v1',expectedEpoch:0})).status,409);
    assert.equal((await request('/api/novels/v1-book/director-version','PUT',{version:'v1',expectedEpoch:1})).status,200);
    assert.equal(await ownership.canExecuteLegacyTask('v1-task'),false,'switching back must not revive old tasks');
    await prisma.novelWorkflowTask.create({data:{id:'v2-opening',title:'V2 开书',lane:'auto_director',status:'queued',directorVersion:'v2'}});
    await prisma.directorRunCommand.create({data:{id:'opening-command',taskId:'v2-opening',commandType:'generate_candidates',idempotencyKey:'v2-open',status:'queued',payloadJson:'{}'}});
    const {DirectorCommandService}=require(path.join(server,'dist/services/novel/director/commands/DirectorCommandService'));
    const commands = new DirectorCommandService();
    assert.equal(await commands.leaseNextCommand({workerId:'v1-worker',leaseMs:30000}),null,'V1 worker cannot lease V2 opening');
    const beforeOpening=await prisma.novelWorkflowTask.findUnique({where:{id:'v2-opening'}});
    await commands.recoverStaleLeases();
    const {DirectorTaskHealingSweep}=require(path.join(server,'dist/workers/directorTaskHealingSweep'));
    await new DirectorTaskHealingSweep().run();
    assert.deepEqual(await prisma.novelWorkflowTask.findUnique({where:{id:'v2-opening'}}),beforeOpening);
    await prisma.novelWorkflowTask.create({data:{id:'v1-opening',title:'V1 开书',lane:'auto_director',status:'queued',directorVersion:'v1'}});
    await prisma.directorRunCommand.create({data:{id:'v1-command',taskId:'v1-opening',commandType:'generate_candidates',idempotencyKey:'v1-open',status:'queued',payloadJson:'{}'}});
    assert.equal((await commands.leaseNextCommand({workerId:'v1-worker',leaseMs:30000})).id,'v1-command');
    assert.equal((await prisma.directorRunCommand.findUnique({where:{id:'opening-command'}})).status,'queued');
    assert.equal((await request('/api/novel-workflows/bootstrap','POST',{lane:'auto_director',workflowTaskId:'v2-opening',seedPayload:{directorVersion:'v1'}})).status,409);
    assert.deepEqual(await prisma.novelWorkflowTask.findUnique({where:{id:'v2-opening'}}),beforeOpening);
    await prisma.directorNextRun.create({data:{id:'foreign-v2-run',novelId:'v1-book',driver:'auto',planVersion:'test',contractJson:JSON.stringify({executionEpoch:2})}});
    await prisma.directorNextRunControl.create({data:{runId:'foreign-v2-run',novelId:'v1-book',status:'queued'}});
    await assert.rejects(ownership.assertV2RunExecution('foreign-v2-run'),error=>error.statusCode===409);
    const controlsBefore=await prisma.directorNextRunControl.findMany();
    const {getDirectorProductionServices}=require(path.join(server,'dist/app/director/services'));
    assert.equal(await getDirectorProductionServices().worker.tick(),false);
    assert.deepEqual(await prisma.directorNextRunControl.findMany(),controlsBefore,'V2 worker cannot lease or transition a V1 novel');
    await prisma.generationJob.create({data:{id:'v2-owned-job',novelId:'v2-book',startOrder:1,endOrder:1,status:'running',heartbeatAt:new Date(0),payload:JSON.stringify({directorNext:{runId:'foreign-v2-run',decisions:[]}})}});
    const jobsBefore=await prisma.generationJob.findMany();
    const {NovelPipelineRuntimeService}=require(path.join(server,'dist/services/novel/NovelPipelineRuntimeService'));
    const watchdog=new NovelPipelineRuntimeService();
    await watchdog.markPendingPipelineJobsForManualRecovery();
    await watchdog.recoverStalePipelineJobs();
    assert.deepEqual(await prisma.generationJob.findMany(),jobsBefore,'V1 startup recovery and watchdog must leave V2 jobs unchanged');
    const {NovelPipelineExecutor}=require(path.join(server,'dist/services/novel/production/NovelPipelineExecutor'));
    await assert.rejects(new NovelPipelineExecutor().execute('v2-owned-job','v2-book',{startOrder:1,endOrder:1}),error=>error.statusCode===409);
    assert.deepEqual(await prisma.generationJob.findMany(),jobsBefore,'foreign pipeline execution must reject before any write');
    const {NovelCorePipelineService}=require(path.join(server,'dist/services/novel/novelCorePipelineService'));
    const pipeline=new NovelCorePipelineService();
    await assert.rejects(pipeline.cancelPipelineJob('v2-owned-job'),error=>error.statusCode===409);
    await assert.rejects(pipeline.resumePipelineJob('v2-owned-job',{expectedOwner:{workflowTaskId:'v1-task'}}),error=>error.statusCode===409);
    assert.deepEqual(await prisma.generationJob.findMany(),jobsBefore,'V1 cancellation must not mutate a V2 job');
    assert.equal(await pipeline.findActivePipelineJobForRange('v2-book',1,1,null,{workflowTaskId:'v1-task'}),null,'V1 range lookup cannot reuse a V2 job');
    assert.equal((await pipeline.findActivePipelineJobForRange('v2-book',1,1)).id,'v2-owned-job','ownerless history lookup stays read-only');
    assert.deepEqual(await prisma.generationJob.findMany(),jobsBefore,'range lookup never cancels another owner');
    await prisma.generationJob.update({where:{id:'v2-owned-job'},data:{status:'failed'}});
    const failedJob=await prisma.generationJob.findUnique({where:{id:'v2-owned-job'}});
    await assert.rejects(pipeline.retryPipelineJob('v2-owned-job'),error=>error.statusCode===409);
    assert.deepEqual(await prisma.generationJob.findUnique({where:{id:'v2-owned-job'}}),failedJob,'V1 retry must not strip V2 ownership');
    await prisma.novelWorkflowTask.create({data:{id:'current-v1-task',title:'当前 V1 任务',novelId:'v1-book',lane:'auto_director',status:'succeeded',directorVersion:'v1',directorEpoch:2}});
    await prisma.generationJob.create({data:{id:'current-v1-job',novelId:'v1-book',startOrder:1,endOrder:1,status:'queued',payload:JSON.stringify({workflowTaskId:'current-v1-task'})}});
    assert.equal((await pipeline.findActivePipelineJobForRange('v1-book',1,1,null,{workflowTaskId:'current-v1-task'})).id,'current-v1-job');
    assert.equal((await pipeline.cancelPipelineJob('current-v1-job')).status,'cancelled','current V1 ownership retains its normal cancellation');
    assert.deepEqual(await prisma.chapter.findUnique({where:{id:'saved'}}), prose);
  } finally {await new Promise(resolve=>http.close(resolve)); await prisma.$disconnect();}
})().catch(error=>{console.error(error);process.exitCode=1;});
`);
  execFileSync(process.execPath, [script], {env:{...process.env,DIRECTOR_NEXT_REPO_ROOT:root,DIRECTOR_NEXT_ENABLED:'true',DATABASE_URL:'file:'+path.join(dir,'test.db').replace(/\\/g,'/'),DATABASE_PROVIDER:'sqlite',AI_NOVEL_RUNTIME:'desktop',AI_NOVEL_APP_DATA_DIR:dir,NODE_ENV:'test'},stdio:'pipe'});
});
