const test=require('node:test'),assert=require('node:assert/strict');const {resolveCacheCapability,applyCacheRequestPolicy,declarePromptCacheBoundary,getPromptCacheBoundary}=require('../dist/platform/llm/cache');
const capability=(model,protocol='openai-compatible',baseURL='https://dashscope.aliyuncs.com/compatible-mode/v1')=>resolveCacheCapability({model,protocol,baseURL});
test('verified official Claude/Qwen requests get only short-TTL content marker without mutation',()=>{for(const [model,protocol,url] of [['qwen-plus','openai-compatible','https://dashscope.aliyuncs.com/compatible-mode/v1'],['claude-sonnet-4-5','anthropic','https://api.anthropic.com/v1']]){const original=protocol==='anthropic'?{system:[{type:'text',text:'稳定规则'}],messages:[{role:'user',content:'本章'}]}:{messages:[{role:'system',content:'稳定规则'},{role:'user',content:'本章'}]};const before=JSON.stringify(original),c=capability(model,protocol,url);assert.equal(c.mode,'explicit');const result=applyCacheRequestPolicy(original,c,{messageIndex:0,contentBlockIndex:0});const block=protocol==='anthropic'?result.system[0]:result.messages[0].content[0];assert.deepEqual(block.cache_control,{type:'ephemeral'});assert.equal(JSON.stringify(original),before);assert.equal(result.messages[1]?.content??result.messages[0]?.content,'本章');assert.equal(result.cache_control,undefined)}});
test('automatic and unknown relay/model paths preserve raw request',()=>{for(const [model,protocol,url] of [['deepseek-chat','openai-compatible','https://api.deepseek.com/v1'],['gpt-4.1','openai-compatible','https://api.openai.com/v1'],['qwen-plus','openai-compatible','http://relay.invalid/v1'],['unknown','anthropic','https://api.anthropic.com/v1'],['llama3','openai-compatible','http://localhost:11434/v1']]){const request={messages:[{role:'system',content:'规则'}]};assert.deepEqual(applyCacheRequestPolicy(request,capability(model,protocol,url),{messageIndex:0,contentBlockIndex:null}),request)}});
test('no boundary, invalid boundary or disabled policy is inert; advanced arrays are unmarked',()=>{const c=capability('qwen-plus'),r={messages:[{role:'system',content:'规则'}]};for(const b of [null,{messageIndex:9,contentBlockIndex:null},{messageIndex:0,contentBlockIndex:2}])assert.deepEqual(applyCacheRequestPolicy(r,c,b),r);const old=process.env.LLM_EXPLICIT_CACHE_ENABLED;process.env.LLM_EXPLICIT_CACHE_ENABLED='false';try{assert.deepEqual(applyCacheRequestPolicy(r,c,{messageIndex:0,contentBlockIndex:0}),r)}finally{if(old===undefined)delete process.env.LLM_EXPLICIT_CACHE_ENABLED;else process.env.LLM_EXPLICIT_CACHE_ENABLED=old}const official=[{}];declarePromptCacheBoundary(official,{messageIndex:0,contentBlockIndex:null});assert.equal(getPromptCacheBoundary(official).messageIndex,0);assert.equal(getPromptCacheBoundary([...official]),null)});

test('actual SDK serialization keeps Qwen cache marker and stream usage option',async()=>{
 const {ChatOpenAI}=require('@langchain/openai');const {SystemMessage,HumanMessage}=require('@langchain/core/messages');const {attachLLMCacheRequestPolicy}=require('../dist/platform/llm/cache');const requests=[];
 const llm=new ChatOpenAI({apiKey:'fixture',model:'qwen-plus',maxRetries:0,configuration:{baseURL:'https://fixture.invalid/v1',fetch:async(url,options)=>{requests.push(JSON.parse(options.body));return new Response('data: '+JSON.stringify({id:'fixture',object:'chat.completion.chunk',created:1,model:'qwen-plus',choices:[],usage:{prompt_tokens:1000,completion_tokens:0,total_tokens:1000,prompt_tokens_details:{cached_tokens:800}}})+'\n\ndata: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}})}}});
 attachLLMCacheRequestPolicy(llm,capability('qwen-plus'));const messages=[new SystemMessage('稳定规则'),new HumanMessage('本章')];declarePromptCacheBoundary(messages,{messageIndex:0,contentBlockIndex:0});for await(const chunk of await llm.stream(messages)){}
 assert.equal(requests.length,1);assert.deepEqual(requests[0].messages[0].content[0].cache_control,{type:'ephemeral'});assert.equal(requests[0].stream_options.include_usage,true);assert.equal(messages[0].content,'稳定规则');
});
test('native adapter places boundary only on stable system block and does not retry provider 400',async()=>{
 const {createAnthropicLLM}=require('../dist/llm/anthropicClient');const {SystemMessage,HumanMessage}=require('@langchain/core/messages');const old=global.fetch;const requests=[];
 global.fetch=async(url,options)=>{requests.push(JSON.parse(options.body));return new Response('original rejection',{status:400})};try{
 const llm=createAnthropicLLM({model:'claude-sonnet-4-5',baseURL:'https://api.anthropic.com/v1',temperature:0});const messages=[new SystemMessage('稳定规则'),new SystemMessage('本章长度'),new HumanMessage('本章')];declarePromptCacheBoundary(messages,{messageIndex:0,contentBlockIndex:0});await assert.rejects(llm.invoke(messages),/original rejection/);assert.equal(requests.length,1);assert.deepEqual(requests[0].system[0].cache_control,{type:'ephemeral'});assert.equal(requests[0].system[1].cache_control,undefined);
 }finally{global.fetch=old}
});

test('native static schema breakpoint survives adjacent Human messages',async()=>{const {createAnthropicLLM}=require('../dist/llm/anthropicClient');const {SystemMessage,HumanMessage}=require('@langchain/core/messages');const old=global.fetch;let request;global.fetch=async(url,options)=>{request=JSON.parse(options.body);return new Response(JSON.stringify({content:[{type:'text',text:'{}'}],usage:{input_tokens:10,output_tokens:2}}))};try{const messages=[new SystemMessage('规则'),new HumanMessage('静态骨架'),new HumanMessage('本章内容')];declarePromptCacheBoundary(messages,{messageIndex:1,contentBlockIndex:0});await createAnthropicLLM({model:'claude-sonnet-4-5',baseURL:'https://api.anthropic.com/v1',temperature:0}).invoke(messages);assert.equal(request.messages.length,1);assert.deepEqual(request.messages[0].content[0].cache_control,{type:'ephemeral'});assert.equal(request.messages[0].content[1].text,'本章内容');assert.equal(request.messages[0].content[1].cache_control,undefined)}finally{global.fetch=old}});
