const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {PrismaInvocationUsageRepository}=require('../dist/platform/llm/usage/infrastructure/PrismaInvocationUsageRepository');
const {InvocationUsageQueryService}=require('../dist/platform/llm/usage/application/InvocationUsageQueryService');
const record=(id='first',runId='new-run',usage={promptTokens:1000,completionTokens:100,totalTokens:1100,inputCache:{cacheHitTokens:800,cacheMissTokens:200,cacheWriteTokens:180,cacheUsageStatus:'reported'}})=>({invocationId:id,runId,generationJobId:null,workflowTaskId:null,novelId:'book',chapterId:'chapter',stage:'writer',provider:'anthropic',model:'fixture',requestProtocol:'anthropic',promptId:'writer',promptVersion:'v1',status:usage?'completed':'failed',startedAt:new Date('2026-10-05'),finishedAt:new Date('2026-10-05'),usage});
function fixture(){const rows=new Map(),warnings=[];const delegate={findUnique:async({where})=>rows.get(where.id)??null,create:async({data})=>{if(rows.has(data.id))throw Object.assign(new Error('duplicate'),{code:'P2002'});rows.set(data.id,data);return data},findMany:async({where})=>[...rows.values()].filter(r=>r.runId===where.runId)};return {rows,warnings,delegate,repo:new PrismaInvocationUsageRepository(delegate,(...args)=>warnings.push(args))}}
test('one terminal invocation id persists once; differing duplicate is diagnosed',async()=>{const f=fixture();await f.repo.record(record());await f.repo.record(record());assert.equal(f.rows.size,1);assert.equal(f.warnings.length,0);await f.repo.record({...record(),model:'changed'});assert.equal(f.rows.get('first').model,'fixture');assert.equal(f.warnings.length,1)});
test('different attempts and unknown failures persist independently without guessed tokens',async()=>{const f=fixture();await f.repo.record(record());await f.repo.record(record('retry'));await f.repo.record(record('failed','new-run',null));assert.equal(f.rows.size,3);assert.equal(f.rows.get('failed').promptTokens,null)});
test('Int overflow preserves identity with unknown counts and diagnostic',async()=>{const f=fixture();await f.repo.record(record('overflow','new-run',{promptTokens:2147483648,completionTokens:1,totalTokens:2147483649}));assert.equal(f.rows.get('overflow').promptTokens,null);assert.equal(f.rows.get('overflow').cacheUsageStatus,'invalid');assert.ok(f.rows.get('overflow').cacheDiagnostic)});
test('query totals all recorded calls, not a page, isolates run, and handles unknown coverage',async()=>{const f=fixture();await f.repo.record(record('a'));await f.repo.record(record('b'));await f.repo.record(record('other','old-run'));const q=new InvocationUsageQueryService(f.delegate);const page=await q.getRunUsage('new-run',{limit:1});assert.equal(page.items.length,1);assert.equal(page.recordedSummary.recordedCallCount,2);assert.equal(page.recordedSummary.inputCache.cacheHitTokens,1600);const next=await q.getRunUsage('new-run',{limit:1,cursor:page.nextCursor});assert.equal(next.items[0].invocationId,'b');await f.repo.record(record('unknown','new-run',null));const mixed=await q.getRunUsage('new-run',{});assert.equal(mixed.recordedSummary.inputCache.cacheHitTokens,null);assert.equal(mixed.recordedSummary.unknownCallCount,1);assert.equal((await q.getRunUsage('empty',{})).recordedSummary.recordedCallCount,0);await assert.rejects(q.getRunUsage('new-run',{cursor:'bad'}),/cursor/)});
test('additive SQLite migration preserves saved chapter and counters in temporary database',()=>{const Database=require('better-sqlite3');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cache-usage-'));const db=new Database(path.join(dir,'fixture.db'));try{db.exec('CREATE TABLE Chapter (id TEXT PRIMARY KEY, content TEXT); CREATE TABLE GenerationJob (totalTokens INTEGER);');db.prepare('INSERT INTO Chapter VALUES (?,?)').run('saved','正文保护');db.exec('INSERT INTO GenerationJob VALUES (87858)');const sql=fs.readFileSync(path.join(__dirname,'../src/prisma/migrations.sqlite/20261005010000_llm_invocation_usage/migration.sql'),'utf8');assert.doesNotMatch(sql,/\b(DROP|DELETE|TRUNCATE)\b/i);db.exec(sql);assert.equal(db.prepare('SELECT content FROM Chapter').get().content,'正文保护');assert.equal(db.prepare('SELECT totalTokens FROM GenerationJob').get().totalTokens,87858);assert.ok(db.prepare("SELECT name FROM sqlite_master WHERE name='LlmInvocationUsageRecord'").get())}finally{db.close();fs.rmSync(dir,{recursive:true,force:true})}});

test('Prisma repository inserts and queries real temporary SQLite records idempotently',async()=>{
 const {PrismaClient}=require('@prisma/client'),{PrismaBetterSqlite3}=require('@prisma/adapter-better-sqlite3'),Database=require('better-sqlite3');
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cache-journal-')),file=path.join(dir,'fixture.db');const db=new Database(file);db.exec(fs.readFileSync(path.join(__dirname,'../src/prisma/migrations.sqlite/20261005010000_llm_invocation_usage/migration.sql'),'utf8'));db.close();
 const client=new PrismaClient({adapter:new PrismaBetterSqlite3({url:'file:'+file})});try{const repo=new PrismaInvocationUsageRepository(client.llmInvocationUsageRecord);await repo.record(record());await repo.record(record());await repo.record(record('second'));const page=await new InvocationUsageQueryService(client.llmInvocationUsageRecord).getRunUsage('new-run',{limit:1});assert.equal(page.recordedSummary.recordedCallCount,2);assert.equal(page.items[0].inputCache.cacheHitTokens,800);assert.ok(page.nextCursor);const next=await new InvocationUsageQueryService(client.llmInvocationUsageRecord).getRunUsage('new-run',{cursor:page.nextCursor});assert.equal(next.items[0].invocationId,'second')}finally{await client.$disconnect();fs.rmSync(dir,{recursive:true,force:true})}
});
